import { AdminUserRecord, AuditLogEntry } from "./types";

export const initialUsers: AdminUserRecord[] = [
  {
    id: "USR-001",
    name: "Ilham Khamsikeaw",
    email: "ilham@gmail.com",
    phone: "011-110-1100",
    primaryLanguage: "Thai",
    spokenLanguages: ["Thai", "English"],
    role: "Admin",
    isLocked: false,
    registeredAt: "2026-08-01 09:00",
    lastActive: "Just now",
  },
  {
    id: "USR-002",
    name: "Taofix yayueri",
    email: "tyayuxri@gmail.com",
    phone: "089-112-3344",
    primaryLanguage: "Thai",
    spokenLanguages: ["Thai", "English", "Japanese"],
    role: "Manager",
    isLocked: false,
    registeredAt: "2026-08-10 14:15",
    lastActive: "10 mins ago",
  },
  {
    id: "USR-003",
    name: "Pakorn Hnusawang",
    email: "pakorn@gmail.com",
    phone: "081-234-5678",
    primaryLanguage: "Thai",
    spokenLanguages: ["Thai", "English", "Mandarin Chinese"],
    role: "Interpreter",
    isLocked: false,
    registeredAt: "2026-08-15 11:20",
    lastActive: "15 mins ago",
    interpreterStats: {
      verificationStatus: "Approved",
      completedMissions: 48,
      rating: 4.95,
      specialties: ["Medical", "Emergency", "Tourism"],
      responseTimeAvg: "1.8 mins",
      feedbackHighlights: [
        "Extremely swift arrival at hospital ER.",
        "Calm, fluent medical translation during surgery intake.",
      ],
    },
  },
  {
    id: "USR-004",
    name: "Lin Wei Chen",
    email: "linwei.c@interpreter.tw",
    phone: "092-987-6543",
    primaryLanguage: "Mandarin Chinese",
    spokenLanguages: ["Mandarin Chinese", "English", "Thai (Conversational)"],
    role: "Interpreter",
    isLocked: false,
    registeredAt: "2026-08-20 16:30",
    lastActive: "1 hour ago",
    interpreterStats: {
      verificationStatus: "Approved",
      completedMissions: 34,
      rating: 4.88,
      specialties: ["Police station", "Legal Documentation", "Immigration"],
      responseTimeAvg: "2.5 mins",
      feedbackHighlights: [
        "Handled difficult police statement translation flawlessly.",
        "Very patient with elderly tourists.",
      ],
    },
  },
  {
    id: "USR-005",
    name: "John Alexander Smith",
    email: "john.smith@uktraveler.co.uk",
    phone: "+44-7700-900077",
    primaryLanguage: "English",
    spokenLanguages: ["English", "French"],
    role: "User",
    isLocked: false,
    registeredAt: "2026-09-01 10:05",
    lastActive: "2 hours ago",
  },
  {
    id: "USR-006",
    name: "Aisha Tanaka",
    email: "aisha.tanaka@tokyomail.jp",
    phone: "086-555-7788",
    primaryLanguage: "Japanese",
    spokenLanguages: ["Japanese", "English", "Thai"],
    role: "Interpreter",
    isLocked: false,
    registeredAt: "2026-08-25 13:40",
    lastActive: "30 mins ago",
    interpreterStats: {
      verificationStatus: "Approved",
      completedMissions: 29,
      rating: 4.92,
      specialties: ["Hospital", "Consular Support", "General Help"],
      responseTimeAvg: "2.1 mins",
      feedbackHighlights: [
        "Supported pregnant tourist in labor ward with utmost empathy.",
      ],
    },
  },
  {
    id: "USR-007",
    name: "Markus Schneider",
    email: "markus.s@deutschland.de",
    phone: "+49-151-555234",
    primaryLanguage: "German",
    spokenLanguages: ["German", "English"],
    role: "User",
    isLocked: true,
    lockReason: "Multiple false SOS distress alerts reported by emergency services",
    registeredAt: "2026-09-02 08:12",
    lastActive: "1 day ago",
  },
  {
    id: "USR-008",
    name: "Chatchai Charoenrat",
    email: "chatchai.c@khvi-support.org",
    phone: "083-444-9988",
    primaryLanguage: "Thai",
    spokenLanguages: ["Thai", "English"],
    role: "Manager",
    isLocked: false,
    registeredAt: "2026-08-18 10:00",
    lastActive: "4 hours ago",
  },
];

export const initialAuditLogs: AuditLogEntry[] = [
  {
    id: "AUD-901",
    timestamp: "2026-09-08 11:45:10",
    actor: "Ilham Khamsikeaw (Admin)",
    action: "ACCOUNT_SUSPEND",
    targetUser: "Markus Schneider (USR-007)",
    severity: "danger",
    details: "Suspended account due to repeated false alarms triggering volunteer dispatch.",
  },
  {
    id: "AUD-902",
    timestamp: "2026-09-08 10:15:32",
    actor: "Kornkanok Wongsuwan (Manager)",
    action: "VOLUNTEER_APPROVE",
    targetUser: "Lin Wei Chen (USR-004)",
    severity: "info",
    details: "Verified police & legal interpreter credentials. Promoted to Active Interpreter tier.",
  },
  {
    id: "AUD-903",
    timestamp: "2026-09-08 09:30:18",
    actor: "Ilham Khamsikeaw (Admin)",
    action: "ROLE_CHANGE",
    targetUser: "Chatchai Charoenrat (USR-008)",
    severity: "warning",
    details: "Promoted from User to Manager role for Bangkok Metropolitan operations.",
  },
  {
    id: "AUD-904",
    timestamp: "2026-09-07 17:20:00",
    actor: "System Engine",
    action: "QUALITY_METRIC_RECALCULATE",
    targetUser: "All Interpreters",
    severity: "info",
    details: "Automated monthly interpreter rating and mission response time indexing executed.",
  },
];

export const AVAILABLE_LANGUAGES = [
  "Thai",
  "English",
  "Mandarin Chinese",
  "Japanese",
  "German",
  "French",
  "Spanish",
  "Korean",
  "Russian",
  "Arabic",
];

export const AVAILABLE_CATEGORIES = [
  "Medical",
  "Emergency",
  "Tourism",
  "Police station",
  "Legal Documentation",
  "Immigration",
  "Hospital",
  "Consular Support",
  "General Help",
];

