import { AdminUserRecord, AuditLogEntry } from "./types";

export const initialUsers: AdminUserRecord[] = [
  {
    id: "USR-001",
    name: "Ilham Khamsikeaw",
    email: "ilham@gmail.com",
    phone: "011-110-1100",
    primaryLanguage: "Thai",
    spokenLanguages: ["Thai", "English"],
    role: "Admin",
    isLocked: false,
    registeredAt: "2026-08-01 09:00",
    lastActive: "Just now",
  },
  {
    id: "USR-002",
    name: "Taofix yayueri",
    email: "tyayuxri@gmail.com",
    phone: "089-112-3344",
    primaryLanguage: "Thai",
    spokenLanguages: ["Thai", "English", "Japanese"],
    role: "Manager",
    isLocked: false,
    registeredAt: "2026-08-10 14:15",
    lastActive: "10 mins ago",
  },
  {
    id: "USR-003",
    name: "Pakorn Hnusawang",
    email: "pakorn@gmail.com",
    phone: "081-234-5678",
    primaryLanguage: "Thai",
    spokenLanguages: ["Thai", "English", "Mandarin Chinese"],
    role: "Interpreter",
    isLocked: false,
    registeredAt: "2026-08-15 11:20",
    lastActive: "15 mins ago",
    interpreterStats: {
      verificationStatus: "Approved",
      completedMissions: 48,
      rating: 4.95,
      specialties: ["Medical", "Emergency", "Tourism"],
      responseTimeAvg: "1.8 mins",
      feedbackHighlights: [
        "Extremely swift arrival at hospital ER.",
        "Calm, fluent medical translation during surgery intake.",
      ],
    },
  },
  {
    id: "USR-004",
    name: "Lin Wei Chen",
    email: "linwei.c@interpreter.tw",
    phone: "092-987-6543",
    primaryLanguage: "Mandarin Chinese",
    spokenLanguages: ["Mandarin Chinese", "English", "Thai (Conversational)"],
    role: "Interpreter",
    isLocked: false,
    registeredAt: "2026-08-20 16:30",
    lastActive: "1 hour ago",
    interpreterStats: {
      verificationStatus: "Approved",
      completedMissions: 34,
      rating: 4.88,
      specialties: ["Police station", "Legal Documentation", "Immigration"],
      responseTimeAvg: "2.5 mins",
      feedbackHighlights: [
        "Handled difficult police statement translation flawlessly.",
        "Very patient with elderly tourists.",
      ],
    },
  },
  {
    id: "USR-005",
    name: "John Alexander Smith",
    email: "john.smith@uktraveler.co.uk",
    phone: "+44-7700-900077",
    primaryLanguage: "English",
    spokenLanguages: ["English", "French"],
    role: "User",
    isLocked: false,
    registeredAt: "2026-09-01 10:05",
    lastActive: "2 hours ago",
  },
  {
    id: "USR-006",
    name: "Aisha Tanaka",
    email: "aisha.tanaka@tokyomail.jp",
    phone: "086-555-7788",
    primaryLanguage: "Japanese",
    spokenLanguages: ["Japanese", "English", "Thai"],
    role: "Interpreter",
    isLocked: false,
    registeredAt: "2026-08-25 13:40",
    lastActive: "30 mins ago",
    interpreterStats: {
      verificationStatus: "Approved",
      completedMissions: 29,
      rating: 4.92,
      specialties: ["Hospital", "Consular Support", "General Help"],
      responseTimeAvg: "2.1 mins",
      feedbackHighlights: [
        "Supported pregnant tourist in labor ward with utmost empathy.",
      ],
    },
  },
  {
    id: "USR-007",
    name: "Markus Schneider",
    email: "markus.s@deutschland.de",
    phone: "+49-151-555234",
    primaryLanguage: "German",
    spokenLanguages: ["German", "English"],
    role: "User",
    isLocked: true,
    lockReason: "Multiple false SOS distress alerts reported by emergency services",
    registeredAt: "2026-09-02 08:12",
    lastActive: "1 day ago",
  },
  {
    id: "USR-008",
    name: "Chatchai Charoenrat",
    email: "chatchai.c@khvi-support.org",
    phone: "083-444-9988",
    primaryLanguage: "Thai",
    spokenLanguages: ["Thai", "English"],
    role: "Manager",
    isLocked: false,
    registeredAt: "2026-08-18 10:00",
    lastActive: "4 hours ago",
  },
  {
    id: "USR-009",
    name: "Tourist John D.",
    email: "john.tourist@example.com",
    phone: "+1-415-555-0199",
    primaryLanguage: "Spanish",
    spokenLanguages: ["Spanish", "English"],
    role: "User",
    isLocked: false,
    registeredAt: "2026-09-03 11:20",
    lastActive: "3 hours ago",
  },
  {
    id: "USR-010",
    name: "Alexei V.",
    email: "alexei.v@volunteer.org",
    phone: "+7-916-555-4321",
    primaryLanguage: "Russian",
    spokenLanguages: ["Russian", "English"],
    role: "Interpreter",
    isLocked: false,
    registeredAt: "2026-08-12 16:45",
    lastActive: "5 hours ago",
    interpreterStats: {
      verificationStatus: "Approved",
      completedMissions: 18,
      rating: 4.12,
      specialties: ["Medical", "Hospital", "Tourism"],
      responseTimeAvg: "4.8 mins",
      feedbackHighlights: [
        "Capable with technical hospital documents.",
        "Under review due to missed ER call without cancellation notice.",
      ],
    },
  },
  {
    id: "USR-011",
    name: "Prapan K.",
    email: "prapan.k@gmail.com",
    phone: "082-345-6789",
    primaryLanguage: "Thai",
    spokenLanguages: ["Thai"],
    role: "User",
    isLocked: false,
    registeredAt: "2026-09-04 09:10",
    lastActive: "Yesterday",
  },
  {
    id: "USR-012",
    name: "Maria Santos",
    email: "maria.santos@languagehub.ph",
    phone: "+63-917-555-8899",
    primaryLanguage: "Japanese",
    spokenLanguages: ["Japanese", "English", "Tagalog"],
    role: "Interpreter",
    isLocked: false,
    registeredAt: "2026-08-05 14:00",
    lastActive: "35 mins ago",
    interpreterStats: {
      verificationStatus: "Approved",
      completedMissions: 27,
      rating: 4.45,
      specialties: ["Immigration", "Airport Transit", "General Help"],
      responseTimeAvg: "2.8 mins",
      feedbackHighlights: [
        "Fast response at airport gate.",
        "Need reminder regarding telephone conduct during official interviews.",
      ],
    },
  },
];

export const initialAuditLogs: AuditLogEntry[] = [
  {
    id: "AUD-901",
    timestamp: "2026-09-08 11:45:10",
    actor: "Ilham Khamsikeaw (Admin)",
    action: "ACCOUNT_SUSPEND",
    targetUser: "Markus Schneider (USR-007)",
    severity: "danger",
    details: "Suspended account due to repeated false alarms triggering volunteer dispatch.",
  },
  {
    id: "AUD-902",
    timestamp: "2026-09-08 10:15:32",
    actor: "Kornkanok Wongsuwan (Manager)",
    action: "VOLUNTEER_APPROVE",
    targetUser: "Lin Wei Chen (USR-004)",
    severity: "info",
    details: "Verified police & legal interpreter credentials. Promoted to Active Interpreter tier.",
  },
  {
    id: "AUD-903",
    timestamp: "2026-09-08 09:30:18",
    actor: "Ilham Khamsikeaw (Admin)",
    action: "ROLE_CHANGE",
    targetUser: "Chatchai Charoenrat (USR-008)",
    severity: "warning",
    details: "Promoted from User to Manager role for Bangkok Metropolitan operations.",
  },
  {
    id: "AUD-904",
    timestamp: "2026-09-07 17:20:00",
    actor: "System Engine",
    action: "SYSTEM_INDEX",
    targetUser: "ALL_INTERPRETERS",
    severity: "info",
    details: "Automated monthly interpreter rating and mission response time indexing executed.",
  },
];

export const initialEscalatedReports: import("./types").AdminIncidentReport[] = [
  {
    id: "REP-302",
    reporterName: "Carlos Mendez",
    reporterRole: "User",
    reportedUserId: "USR-009",
    reportedUserName: "Tourist John D.",
    reportedUserRole: "User",
    bookingId: "BKG-9844",
    reason: "Aggressive verbal harassment, demanding off-platform unauthorized guiding services, and refused payment settlement.",
    originalReason: "Acoso verbal agresivo, exigió servicios de guía no autorizados fuera de la plataforma y se negó a liquidar el pago.",
    originalLanguage: "Spanish",
    severity: "critical",
    createdAt: "2026-09-06 14:15",
    status: "Escalated to Admin",
    actionTaken: "Escalated by Manager (Vipa) for Super Admin permanent ban review (FR-18, FR-20).",
  },
  {
    id: "REP-301",
    reporterName: "Elena Petrova",
    reporterRole: "User",
    reportedUserId: "USR-010",
    reportedUserName: "Alexei V.",
    reportedUserRole: "Interpreter",
    bookingId: "BKG-9920",
    reason: "Interpreter did not attend emergency medical triage without prior cancellation notice, putting patient at severe risk.",
    originalReason: "Переводчик не явился на экстренный медицинский прием без предварительного уведомления об отмене.",
    originalLanguage: "Russian",
    severity: "high",
    createdAt: "2026-09-07 19:40",
    status: "Escalated to Admin",
    actionTaken: "Escalated by Manager for interpreter credential lock or suspension.",
  },
  {
    id: "REP-303",
    reporterName: "Volunteer Somsak",
    reporterRole: "Interpreter",
    reportedUserId: "USR-011",
    reportedUserName: "Prapan K.",
    reportedUserRole: "User",
    bookingId: "BKG-9710",
    reason: "Suspected fraudulent emergency request to evade police inspection checkpoint and transport prohibited goods.",
    originalReason: "ผู้ใช้แจ้งเหตุฉุกเฉินเท็จเพื่อใช้ล่ามช่วยเจรจาหลบเลี่ยงด่านตรวจตำรวจและลักลอบขนส่งสิ่งของผิดกฎหมาย",
    originalLanguage: "Thai",
    severity: "critical",
    createdAt: "2026-09-08 10:20",
    status: "Escalated to Admin",
    actionTaken: "High-priority safety flag submitted by Manager.",
  },
  {
    id: "REP-304",
    reporterName: "Kenji Sato",
    reporterRole: "User",
    reportedUserId: "USR-012",
    reportedUserName: "Maria Santos",
    reportedUserRole: "Interpreter",
    bookingId: "BKG-9632",
    reason: "Interpreter repeatedly answered private phone calls during immigration interview, causing communication delay.",
    originalReason: "入国審査の面接中に通訳者が私用電話を繰り返し取り、手続きが大幅に遅延しました。",
    originalLanguage: "Japanese",
    severity: "medium",
    createdAt: "2026-09-09 11:30",
    status: "Escalated to Admin",
    actionTaken: "Manager requested behavioral warning or temporary counseling suspension.",
  },
];


export const AVAILABLE_LANGUAGES = [
  "Thai",
  "English",
  "Mandarin Chinese",
  "Japanese",
  "German",
  "French",
  "Spanish",
  "Korean",
  "Russian",
  "Arabic",
];

export const AVAILABLE_CATEGORIES = [
  "Medical",
  "Emergency",
  "Tourism",
  "Police station",
  "Legal Documentation",
  "Immigration",
  "Hospital",
  "Consular Support",
  "General Help",
];

export const initialSystemSettings = {
  // 1. Emergency Dispatch & SOS Policy
  sosDispatchRadiusKm: 15,
  autoEscalateTicketMinutes: 20,
  allowGuestSosRequests: false,

  // 2. Interpreter Accreditation & Platform Safeguards
  interpreterMinRatingThreshold: 3.5,
  mandatoryIdVerification: true,
  maxFalseAlarmsBeforeAutoLock: 3,

  // 3. Taxonomies & Catalogs
  languagesCatalog: [...AVAILABLE_LANGUAGES],
  specialtyCategories: [...AVAILABLE_CATEGORIES],

  // Metadata
  lastUpdated: "2026-09-17 10:00:00",
  updatedBy: "Ilham Khamsikeaw (Super Admin)",
};
