import { InterpreterApplicant, HelpTicket, IncidentReport } from "./types";

export const initialApplicants: InterpreterApplicant[] = [
  {
    id: "APP-101",
    name: "Sompong Vorakul",
    age: 32,
    country: "Thailand",
    primaryLanguage: "Thai",
    spokenLanguages: ["Thai", "Mandarin Chinese"],
    specialtyCategories: ["Medical", "Tourism"],
    experienceSummary: "5 years volunteer medical translator at community clinics and emergency relief stations in Bangkok.",
    contactChannels: "Line: sompong_v | Tel: 081-234-5678",
    appliedDate: "2026-09-07 14:20",
    status: "Pending",
    backgroundCheck: "Passed",
    proficiencyScore: "Native Thai, HSK 5 (Mandarin)",
    document: {
      name: "Medical_Interpreting_Cert.pdf",
      type: "cert",
      format: "pdf",
      size: "2.1 MB",
    },
  },
  {
    id: "APP-102",
    name: "Lin Wei Chen",
    age: 28,
    country: "Taiwan",
    primaryLanguage: "Mandarin Chinese",
    spokenLanguages: ["Mandarin Chinese", "English"],
    specialtyCategories: ["Police station", "Legal Documentation"],
    experienceSummary: "Certified legal and administrative interpreter in Taipei, fluent in consular procedures and consular crisis aid.",
    contactChannels: "WeChat: linwei_tw | Email: linwei@example.com",
    appliedDate: "2026-09-07 11:05",
    status: "Under Review",
    backgroundCheck: "Passed",
    proficiencyScore: "TOCFL Level 6 (Native), IELTS 8.0",
    document: {
      name: "Legal_Translation_License.pdf",
      type: "cert",
      format: "pdf",
      size: "3.5 MB",
    },
  },
  {
    id: "APP-103",
    name: "Aung Myo Zaw",
    age: 26,
    country: "Myanmar",
    primaryLanguage: "Burmese",
    spokenLanguages: ["Burmese"],
    specialtyCategories: ["Labour Assistance", "Medical"],
    experienceSummary: "Active frontline interpreter for Myanmar migrant worker health clinic and hospital emergency ward in Samut Sakhon.",
    contactChannels: "Viber: aungmyo_zaw | Tel: 089-876-5432",
    appliedDate: "2026-09-06 18:40",
    status: "Pending",
    backgroundCheck: "Passed",
    proficiencyScore: "Native Burmese Fluency",
    document: {
      name: "Community_Health_Volunteer_Cert.png",
      type: "cert",
      format: "png",
      size: "1.8 MB",
    },
  },
  {
    id: "APP-104",
    name: "Nguyen Thi Mai",
    age: 30,
    country: "Vietnam",
    primaryLanguage: "Vietnamese",
    spokenLanguages: ["Vietnamese"],
    specialtyCategories: ["Tourism", "Police station"],
    experienceSummary: "Tourism and immigration assistance coordinator for Vietnamese travelers and expatriates.",
    contactChannels: "Zalo: mai_nguyen | Tel: 092-345-6789",
    appliedDate: "2026-09-05 09:15",
    status: "Under Review",
    backgroundCheck: "Requires Review",
    proficiencyScore: "C2 Vietnamese (Native)",
    document: {
      name: "Tourism_Guild_Badge.jpg",
      type: "cert",
      format: "jpg",
      size: "1.2 MB",
    },
  },
  {
    id: "APP-105",
    name: "Kenji Tanaka",
    age: 35,
    country: "Japan",
    primaryLanguage: "Japanese",
    spokenLanguages: ["Japanese", "English"],
    specialtyCategories: ["Medical", "Tourism"],
    experienceSummary: "Former consular aid assistant in Bangkok, experienced with disaster evacuation and hospital referrals.",
    contactChannels: "Line: kenji_t | Email: kenji.tanaka@example.jp",
    appliedDate: "2026-09-04 16:30",
    status: "Approved",
    backgroundCheck: "Passed",
    proficiencyScore: "JLPT N1 (Native), TOEIC 920",
    document: {
      name: "Medical_Volunteering_Record.pdf",
      type: "cert",
      format: "pdf",
      size: "1.5 MB",
    },
  },
  {
    id: "APP-106",
    name: "Elena Rostova",
    age: 29,
    country: "Russia",
    primaryLanguage: "Russian",
    spokenLanguages: ["Russian", "English"],
    specialtyCategories: ["Tourism"],
    experienceSummary: "Hospitality assistance volunteer for Russian tourists in Phuket and Pattaya area.",
    contactChannels: "Telegram: elena_rost | Tel: 095-112-2334",
    appliedDate: "2026-09-03 13:00",
    status: "Rejected",
    rejectionReason: "Incomplete documentation: missing primary identity verification and criminal record clearance certificate.",
    backgroundCheck: "Requires Review",
    proficiencyScore: "Native Russian, IELTS 7.5",
    document: {
      name: "Translation_Credentials.pdf",
      type: "cv",
      format: "pdf",
      size: "450 KB",
    },
  },
];

export const initialTickets: HelpTicket[] = [
  {
    id: "HLP-801",
    requesterName: "Mei Ling Zhang",
    requesterRole: "User",
    category: "Communication",
    missionId: "MSN-4421",
    title: "Interpreter cannot arrive at emergency room in time",
    detail: "Current traffic blockage around Din Daeng. Need immediate alternative interpreter or remote phone assist.",
    createdAt: "10 mins ago",
    status: "Open",
    urgency: "urgent",
  },
  {
    id: "HLP-802",
    requesterName: "David Miller",
    requesterRole: "Interpreter",
    category: "Safety",
    missionId: "MSN-4418",
    title: "Requester location appears different from map coordinate",
    detail: "Arrived at Bang Rak junction, but requester notes mention a building 1 km further east.",
    createdAt: "35 mins ago",
    status: "In Progress",
    urgency: "normal",
    response: "Manager contacted requester via WhatsApp to send real-time pinpoint location.",
  },
];

export const initialReports: IncidentReport[] = [
  {
    id: "REP-301",
    reporterName: "Dr. Somchai (ER Chula)",
    reporterRole: "User",
    reportedUserName: "Alexei V.",
    reportedUserRole: "Interpreter",
    bookingId: "BKG-9920",
    reason: "Interpreter failed to show up without prior cancellation notice during emergency patient admission.",
    originalReason: "Переводчик не явился на экстренный медицинский прием без предварительного уведомления об отмене.",
    originalLanguage: "Russian",
    severity: "high",
    createdAt: "2026-09-07 19:40",
    status: "Pending Investigation",
  },
  {
    id: "REP-302",
    reporterName: "Kanya S. (Volunteer)",
    reporterRole: "Interpreter",
    reportedUserName: "Tourist John D.",
    reportedUserRole: "User",
    bookingId: "BKG-9844",
    reason: "Verbal misconduct and demanding off-platform private guiding beyond medical translation scope.",
    originalReason: "Acoso verbal agresivo, exigió servicios de guía no autorizados fuera de la plataforma y se negó a liquidar el pago.",
    originalLanguage: "Spanish",
    severity: "critical",
    createdAt: "2026-09-06 14:15",
    status: "Escalated to Admin",
    actionTaken: "Escalated to Admin Portal for user account lock evaluation (FR-78, FR-80).",
  },
  {
    id: "REP-304",
    reporterName: "Lin Wei Chen",
    reporterRole: "Interpreter",
    reportedUserName: "Prapan K.",
    reportedUserRole: "User",
    bookingId: "BKG-9688",
    reason: "Requester was delayed by 30 minutes due to unexpected traffic and miscommunicated the meeting point.",
    originalReason: "求助者因塞車遲到30分鐘，且會面地點溝通有誤，現場已順利會合但記錄時間有爭議。",
    originalLanguage: "Mandarin Chinese",
    severity: "medium",
    createdAt: "2026-09-08 09:15",
    status: "Pending Investigation",
  },
];

export const initialManagerActivities = [
  {
    id: "ACT-101",
    timestamp: "10 mins ago",
    type: "approval" as const,
    targetName: "Sompong Vorakul",
    description: "Approved volunteer interpreter application for Thai-Mandarin Chinese pair (Medical & Tourism).",
  },
  {
    id: "ACT-102",
    timestamp: "35 mins ago",
    type: "ticket_reply" as const,
    targetName: "David Miller (HLP-802)",
    description: "Contacted requester via WhatsApp to resolve pinpoint location mismatch in Bang Rak.",
  },
  {
    id: "ACT-103",
    timestamp: "2 hours ago",
    type: "rejection" as const,
    targetName: "Pham Thi Hoa",
    description: "Rejected application due to expired medical translation certificate (Re-apply eligible in 30 days).",
  },
  {
    id: "ACT-104",
    timestamp: "Yesterday, 14:15",
    type: "report_escalation" as const,
    targetName: "Tourist John D. (REP-302)",
    description: "Escalated verbal misconduct incident to Super Admin for account suspension evaluation.",
  },
];

export function formatBadgeCount(count: number): string {
  if (count > 99) return "99+";
  return count.toString();
}

