-- First database-backed domain slice for the currently implemented interpreter flow.
-- Supabase Auth remains the source of truth for identity and sessions.

create table if not exists public.languages (
  language_id bigint generated by default as identity primary key,
  language_code text not null unique,
  language_name text not null,
  language_name_th text,
  language_name_zh text,
  is_active boolean not null default true,
  created_at timestamptz not null default timezone('utc', now()),
  constraint languages_code_format check (language_code ~ '^[a-z0-9-]+$')
);

insert into public.languages (language_code, language_name, language_name_th, language_name_zh)
values
  ('burmese', 'Burmese', 'ภาษาพม่า', '缅甸语'),
  ('chinese', 'Chinese', 'ภาษาจีน', '中文'),
  ('english', 'English', 'ภาษาอังกฤษ', '英语'),
  ('vietnamese', 'Vietnamese', 'ภาษาเวียดนาม', '越南语'),
  ('sign', 'Thai sign language', 'ภาษามือไทย', '泰国手语')
on conflict (language_code) do nothing;

alter table public.languages enable row level security;
revoke all on table public.languages from anon;
revoke all on table public.languages from authenticated;
grant select on table public.languages to authenticated;
drop policy if exists languages_read_authenticated on public.languages;
create policy languages_read_authenticated
  on public.languages
  for select
  to authenticated
  using (is_active = true);

create table if not exists public.categories (
  category_id bigint generated by default as identity primary key,
  category_code text not null unique,
  category_name text not null,
  category_name_th text,
  category_name_zh text,
  icon text,
  is_active boolean not null default true,
  created_at timestamptz not null default timezone('utc', now()),
  constraint categories_code_format check (category_code ~ '^[a-z0-9-]+$')
);

insert into public.categories (category_code, category_name, category_name_th, category_name_zh, icon)
values
  ('medical', 'Medical', 'การแพทย์และโรงพยาบาล', '医疗与医院', '🏥'),
  ('police', 'Police station', 'สถานีตำรวจและคดีความ', '警察局与法律事务', '👮'),
  ('government', 'Government office', 'หน่วยงานราชการ', '政府机构', '🏛️'),
  ('accident', 'Accident scene', 'อุบัติเหตุและเหตุฉุกเฉิน', '事故与紧急情况', '🚨'),
  ('school', 'School', 'โรงเรียนและการศึกษา', '学校与教育', '🏫')
on conflict (category_code) do nothing;

alter table public.categories enable row level security;
revoke all on table public.categories from anon;
revoke all on table public.categories from authenticated;
grant select on table public.categories to authenticated;
drop policy if exists categories_read_authenticated on public.categories;
create policy categories_read_authenticated
  on public.categories
  for select
  to authenticated
  using (is_active = true);

create table if not exists public.interpreter_applications (
  application_id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(user_id) on delete cascade,
  applicant_name text not null,
  phone text not null,
  email text not null,
  age smallint,
  extra_contact text,
  assigned_area text,
  certificate_file_name text not null,
  certificate_url text,
  work_history jsonb not null default '[]'::jsonb,
  documents jsonb not null default '[]'::jsonb,
  status text not null default 'pending',
  reject_reason text,
  revision_note text,
  cancellation_reason text,
  submitted_at timestamptz not null default timezone('utc', now()),
  reviewed_at timestamptz,
  reviewed_by_user_id uuid references public.profiles(user_id) on delete set null,
  cancelled_at timestamptz,
  cancelled_by_user_id uuid references public.profiles(user_id) on delete set null,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  constraint interpreter_applications_age_check
    check (age is null or age between 13 and 120),
  constraint interpreter_applications_status_check
    check (status in ('pending', 'under_review', 'needs_revision', 'approved', 'rejected', 'cancelled')),
  constraint interpreter_applications_work_history_array_check
    check (jsonb_typeof(work_history) = 'array'),
  constraint interpreter_applications_documents_array_check
    check (jsonb_typeof(documents) = 'array')
);

create index if not exists interpreter_applications_user_id_idx
  on public.interpreter_applications(user_id);
create index if not exists interpreter_applications_status_idx
  on public.interpreter_applications(status);
create unique index if not exists interpreter_applications_one_active_per_user_idx
  on public.interpreter_applications(user_id)
  where status <> 'cancelled';

alter table public.interpreter_applications enable row level security;
revoke all on table public.interpreter_applications from anon;
revoke all on table public.interpreter_applications from authenticated;
grant select, insert, update on table public.interpreter_applications to authenticated;
grant usage, select on sequence public.interpreter_applications_application_id_seq to authenticated;

drop policy if exists interpreter_applications_select_own_or_staff on public.interpreter_applications;
create policy interpreter_applications_select_own_or_staff
  on public.interpreter_applications
  for select
  to authenticated
  using (
    (select auth.uid()) = user_id
    or exists (
      select 1
      from public.profiles p
      where p.user_id = (select auth.uid())
        and p.role in ('Manager', 'Admin')
    )
  );

drop policy if exists interpreter_applications_insert_own on public.interpreter_applications;
create policy interpreter_applications_insert_own
  on public.interpreter_applications
  for insert
  to authenticated
  with check ((select auth.uid()) = user_id);

drop policy if exists interpreter_applications_update_own_or_staff on public.interpreter_applications;
create policy interpreter_applications_update_own_or_staff
  on public.interpreter_applications
  for update
  to authenticated
  using (
    (select auth.uid()) = user_id
    or exists (
      select 1
      from public.profiles p
      where p.user_id = (select auth.uid())
        and p.role in ('Manager', 'Admin')
    )
  )
  with check (
    (select auth.uid()) = user_id
    or exists (
      select 1
      from public.profiles p
      where p.user_id = (select auth.uid())
        and p.role in ('Manager', 'Admin')
    )
  );

create trigger interpreter_applications_set_updated_at
  before update on public.interpreter_applications
  for each row
  execute function private.set_updated_at();

create table if not exists public.interpreter_application_languages (
  application_id bigint not null references public.interpreter_applications(application_id) on delete cascade,
  language_id bigint not null references public.languages(language_id) on delete restrict,
  language_level text,
  is_primary boolean not null default false,
  created_at timestamptz not null default timezone('utc', now()),
  primary key (application_id, language_id)
);

create index if not exists interpreter_application_languages_language_id_idx
  on public.interpreter_application_languages(language_id);

alter table public.interpreter_application_languages enable row level security;
revoke all on table public.interpreter_application_languages from anon;
revoke all on table public.interpreter_application_languages from authenticated;
grant select, insert, delete on table public.interpreter_application_languages to authenticated;

drop policy if exists interpreter_application_languages_select_own_or_staff on public.interpreter_application_languages;
create policy interpreter_application_languages_select_own_or_staff
  on public.interpreter_application_languages
  for select
  to authenticated
  using (
    exists (
      select 1
      from public.interpreter_applications a
      where a.application_id = interpreter_application_languages.application_id
        and (
          a.user_id = (select auth.uid())
          or exists (
            select 1
            from public.profiles p
            where p.user_id = (select auth.uid())
              and p.role in ('Manager', 'Admin')
          )
        )
    )
  );

drop policy if exists interpreter_application_languages_insert_own_or_staff on public.interpreter_application_languages;
create policy interpreter_application_languages_insert_own_or_staff
  on public.interpreter_application_languages
  for insert
  to authenticated
  with check (
    exists (
      select 1
      from public.interpreter_applications a
      where a.application_id = interpreter_application_languages.application_id
        and (
          a.user_id = (select auth.uid())
          or exists (
            select 1
            from public.profiles p
            where p.user_id = (select auth.uid())
              and p.role in ('Manager', 'Admin')
          )
        )
    )
  );

drop policy if exists interpreter_application_languages_delete_own_or_staff on public.interpreter_application_languages;
create policy interpreter_application_languages_delete_own_or_staff
  on public.interpreter_application_languages
  for delete
  to authenticated
  using (
    exists (
      select 1
      from public.interpreter_applications a
      where a.application_id = interpreter_application_languages.application_id
        and (
          a.user_id = (select auth.uid())
          or exists (
            select 1
            from public.profiles p
            where p.user_id = (select auth.uid())
              and p.role in ('Manager', 'Admin')
          )
        )
    )
  );

create table if not exists public.interpreter_application_categories (
  application_id bigint not null references public.interpreter_applications(application_id) on delete cascade,
  category_id bigint not null references public.categories(category_id) on delete restrict,
  created_at timestamptz not null default timezone('utc', now()),
  primary key (application_id, category_id)
);

create index if not exists interpreter_application_categories_category_id_idx
  on public.interpreter_application_categories(category_id);

alter table public.interpreter_application_categories enable row level security;
revoke all on table public.interpreter_application_categories from anon;
revoke all on table public.interpreter_application_categories from authenticated;
grant select, insert, delete on table public.interpreter_application_categories to authenticated;

drop policy if exists interpreter_application_categories_select_own_or_staff on public.interpreter_application_categories;
create policy interpreter_application_categories_select_own_or_staff
  on public.interpreter_application_categories
  for select
  to authenticated
  using (
    exists (
      select 1
      from public.interpreter_applications a
      where a.application_id = interpreter_application_categories.application_id
        and (
          a.user_id = (select auth.uid())
          or exists (
            select 1
            from public.profiles p
            where p.user_id = (select auth.uid())
              and p.role in ('Manager', 'Admin')
          )
        )
    )
  );

drop policy if exists interpreter_application_categories_insert_own_or_staff on public.interpreter_application_categories;
create policy interpreter_application_categories_insert_own_or_staff
  on public.interpreter_application_categories
  for insert
  to authenticated
  with check (
    exists (
      select 1
      from public.interpreter_applications a
      where a.application_id = interpreter_application_categories.application_id
        and (
          a.user_id = (select auth.uid())
          or exists (
            select 1
            from public.profiles p
            where p.user_id = (select auth.uid())
              and p.role in ('Manager', 'Admin')
          )
        )
    )
  );

drop policy if exists interpreter_application_categories_delete_own_or_staff on public.interpreter_application_categories;
create policy interpreter_application_categories_delete_own_or_staff
  on public.interpreter_application_categories
  for delete
  to authenticated
  using (
    exists (
      select 1
      from public.interpreter_applications a
      where a.application_id = interpreter_application_categories.application_id
        and (
          a.user_id = (select auth.uid())
          or exists (
            select 1
            from public.profiles p
            where p.user_id = (select auth.uid())
              and p.role in ('Manager', 'Admin')
          )
        )
    )
  );
