-- Database-backed interpreter profile change requests for Manager review.
-- Requests are retained as history. Approving a request updates the active
-- interpreter application relations in the same transaction.

create table if not exists public.interpreter_profile_change_requests (
  request_id bigint generated by default as identity primary key,
  interpreter_user_id uuid not null references public.profiles(user_id) on delete cascade,
  application_id bigint not null references public.interpreter_applications(application_id) on delete cascade,
  request_type text not null,
  current_languages jsonb not null default '[]'::jsonb,
  requested_languages jsonb not null default '[]'::jsonb,
  current_categories jsonb not null default '[]'::jsonb,
  requested_categories jsonb not null default '[]'::jsonb,
  reason text not null,
  evidence_files jsonb not null default '[]'::jsonb,
  status text not null default 'pending_review',
  review_note text,
  submitted_at timestamptz not null default timezone('utc', now()),
  reviewed_at timestamptz,
  reviewed_by_user_id uuid references public.profiles(user_id) on delete set null,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  constraint interpreter_profile_change_requests_type_check
    check (request_type in ('language', 'category', 'both')),
  constraint interpreter_profile_change_requests_status_check
    check (status in ('pending_review', 'changes_requested', 'approved', 'rejected')),
  constraint interpreter_profile_change_requests_reason_check
    check (length(trim(reason)) > 0),
  constraint interpreter_profile_change_requests_current_languages_array_check
    check (jsonb_typeof(current_languages) = 'array'),
  constraint interpreter_profile_change_requests_requested_languages_array_check
    check (jsonb_typeof(requested_languages) = 'array'),
  constraint interpreter_profile_change_requests_current_categories_array_check
    check (jsonb_typeof(current_categories) = 'array'),
  constraint interpreter_profile_change_requests_requested_categories_array_check
    check (jsonb_typeof(requested_categories) = 'array'),
  constraint interpreter_profile_change_requests_evidence_files_array_check
    check (jsonb_typeof(evidence_files) = 'array')
);

create index if not exists interpreter_profile_change_requests_interpreter_idx
  on public.interpreter_profile_change_requests(interpreter_user_id);
create index if not exists interpreter_profile_change_requests_application_idx
  on public.interpreter_profile_change_requests(application_id);
create index if not exists interpreter_profile_change_requests_status_submitted_idx
  on public.interpreter_profile_change_requests(status, submitted_at desc);

alter table public.interpreter_profile_change_requests enable row level security;
revoke all on table public.interpreter_profile_change_requests from anon, authenticated;
grant select, insert on table public.interpreter_profile_change_requests to authenticated;
grant usage, select on sequence public.interpreter_profile_change_requests_request_id_seq to authenticated;

create or replace function private.is_profile_change_staff()
returns boolean
language sql
security definer
stable
set search_path = ''
as $$
  select exists (
    select 1
    from public.profiles
    where user_id = (select auth.uid())
      and role in ('Manager', 'Admin')
      and is_locked = false
  );
$$;

revoke all on function private.is_profile_change_staff() from public;
grant usage on schema private to authenticated;
grant execute on function private.is_profile_change_staff() to authenticated;

drop policy if exists interpreter_profile_change_requests_select on public.interpreter_profile_change_requests;
create policy interpreter_profile_change_requests_select
  on public.interpreter_profile_change_requests
  for select
  to authenticated
  using (
    interpreter_user_id = (select auth.uid())
    or (select private.is_profile_change_staff())
  );

drop policy if exists interpreter_profile_change_requests_insert_own on public.interpreter_profile_change_requests;
create policy interpreter_profile_change_requests_insert_own
  on public.interpreter_profile_change_requests
  for insert
  to authenticated
  with check (
    interpreter_user_id = (select auth.uid())
    and status = 'pending_review'
    and reviewed_at is null
    and reviewed_by_user_id is null
    and exists (
      select 1
      from public.interpreter_applications a
      where a.application_id = interpreter_profile_change_requests.application_id
        and a.user_id = (select auth.uid())
        and a.status = 'approved'
    )
  );

drop trigger if exists interpreter_profile_change_requests_set_updated_at
  on public.interpreter_profile_change_requests;
create trigger interpreter_profile_change_requests_set_updated_at
  before update on public.interpreter_profile_change_requests
  for each row
  execute function private.set_updated_at();

create or replace function public.review_interpreter_profile_change_request(
  p_request_id bigint,
  p_decision text,
  p_note text default null
)
returns void
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  current_user_id uuid := (select auth.uid());
  actor_role text;
  target_user_id uuid;
  target_application_id bigint;
  target_status text;
  target_request_type text;
  target_requested_languages jsonb;
  target_requested_categories jsonb;
begin
  if current_user_id is null then
    raise exception 'not_authenticated' using errcode = '42501';
  end if;

  select role into actor_role
  from public.profiles
  where user_id = current_user_id;

  if actor_role is null or actor_role not in ('Manager', 'Admin') then
    raise exception 'manager_role_required' using errcode = '42501';
  end if;
  if exists (
    select 1
    from public.profiles
    where user_id = current_user_id
      and is_locked = true
  ) then
    raise exception 'manager_account_locked' using errcode = '42501';
  end if;
  if p_decision not in ('approved', 'changes_requested', 'rejected') then
    raise exception 'invalid_profile_change_decision';
  end if;
  if p_decision in ('changes_requested', 'rejected')
     and length(trim(coalesce(p_note, ''))) = 0 then
    raise exception 'review_note_required';
  end if;

  select
    interpreter_user_id,
    application_id,
    status,
    request_type,
    requested_languages,
    requested_categories
  into
    target_user_id,
    target_application_id,
    target_status,
    target_request_type,
    target_requested_languages,
    target_requested_categories
  from public.interpreter_profile_change_requests
  where request_id = p_request_id
  for update;

  if target_user_id is null then
    raise exception 'profile_change_request_not_found';
  end if;
  if target_status not in ('pending_review', 'changes_requested') then
    raise exception 'profile_change_request_already_decided';
  end if;

  if p_decision = 'approved' then
    if target_request_type in ('language', 'both') then
      if exists (
        select 1
        from jsonb_array_elements(target_requested_languages) as item
        where case
          when (item ->> 'id') ~ '^[0-9]+$' then not exists (
            select 1
            from public.languages l
            where l.language_id = (item ->> 'id')::bigint
              and l.is_active = true
          )
          else true
        end
      ) then
        raise exception 'invalid_requested_language';
      end if;

      delete from public.interpreter_application_languages
      where application_id = target_application_id;

      insert into public.interpreter_application_languages (
        application_id,
        language_id,
        language_level,
        is_primary
      )
      select
        target_application_id,
        (item ->> 'id')::bigint,
        nullif(item ->> 'level', ''),
        case
          when (item ->> 'is_primary') in ('true', 'false')
            then (item ->> 'is_primary')::boolean
          else false
        end
      from jsonb_array_elements(target_requested_languages) as item;
    end if;

    if target_request_type in ('category', 'both') then
      if exists (
        select 1
        from jsonb_array_elements(target_requested_categories) as item
        where case
          when (item ->> 'id') ~ '^[0-9]+$' then not exists (
            select 1
            from public.categories c
            where c.category_id = (item ->> 'id')::bigint
              and c.is_active = true
          )
          else true
        end
      ) then
        raise exception 'invalid_requested_category';
      end if;

      delete from public.interpreter_application_categories
      where application_id = target_application_id;

      insert into public.interpreter_application_categories (
        application_id,
        category_id
      )
      select
        target_application_id,
        (item ->> 'id')::bigint
      from jsonb_array_elements(target_requested_categories) as item;
    end if;

    update public.interpreter_applications
    set updated_at = timezone('utc', now())
    where application_id = target_application_id;
  end if;

  update public.interpreter_profile_change_requests
  set status = p_decision,
      review_note = nullif(trim(coalesce(p_note, '')), ''),
      reviewed_at = timezone('utc', now()),
      reviewed_by_user_id = current_user_id
  where request_id = p_request_id;
end;
$$;

revoke all on function public.review_interpreter_profile_change_request(bigint, text, text) from public;
grant execute on function public.review_interpreter_profile_change_request(bigint, text, text) to authenticated;
