create table if not exists public.system_audit_logs (
  audit_log_id bigint generated by default as identity primary key,
  actor_id uuid references public.profiles(user_id) on delete set null,
  actor_name text not null,
  actor_role text not null check (actor_role in ('Admin', 'Manager', 'System')),
  action text not null check (length(trim(action)) between 1 and 100),
  target_user text not null,
  severity text not null check (severity in ('info', 'warning', 'danger')),
  details text not null,
  created_at timestamptz not null default timezone('utc', now())
);

create index if not exists system_audit_logs_created_at_idx
  on public.system_audit_logs(created_at desc);

create index if not exists system_audit_logs_actor_role_idx
  on public.system_audit_logs(actor_role);

alter table public.system_audit_logs enable row level security;
revoke all on table public.system_audit_logs from anon, authenticated;
grant select, insert on table public.system_audit_logs to authenticated;
grant usage, select on sequence public.system_audit_logs_audit_log_id_seq to authenticated;

drop policy if exists system_audit_logs_select_admin on public.system_audit_logs;
create policy system_audit_logs_select_admin
  on public.system_audit_logs
  for select
  to authenticated
  using (
    exists (
      select 1
      from public.profiles p
      where p.user_id = (select auth.uid())
        and p.role = 'Admin'
        and not p.is_locked
    )
  );

drop policy if exists system_audit_logs_insert_staff on public.system_audit_logs;
create policy system_audit_logs_insert_staff
  on public.system_audit_logs
  for insert
  to authenticated
  with check (
    actor_id = (select auth.uid())
    and exists (
      select 1
      from public.profiles p
      where p.user_id = (select auth.uid())
        and p.role in ('Manager', 'Admin')
        and not p.is_locked
    )
  );

create table if not exists public.platform_settings (
  setting_key text primary key,
  settings jsonb not null check (jsonb_typeof(settings) = 'object'),
  updated_at timestamptz not null default timezone('utc', now()),
  updated_by uuid references public.profiles(user_id) on delete set null
);

insert into public.platform_settings (setting_key, settings)
values (
  'default',
  '{
    "sosDispatchRadiusKm": 15,
    "autoEscalateTicketMinutes": 20,
    "allowGuestSosRequests": false,
    "interpreterMinRatingThreshold": 3.5,
    "mandatoryIdVerification": true,
    "maxFalseAlarmsBeforeAutoLock": 3,
    "languagesCatalog": ["Thai", "English", "Mandarin Chinese", "Japanese", "German", "French", "Spanish", "Korean", "Russian", "Arabic"],
    "specialtyCategories": ["Medical", "Emergency", "Tourism", "Police station", "Legal Documentation", "Immigration", "Hospital", "Consular Support", "General Help"]
  }'::jsonb
)
on conflict (setting_key) do nothing;

drop trigger if exists platform_settings_set_updated_at on public.platform_settings;
create trigger platform_settings_set_updated_at
  before update on public.platform_settings
  for each row
  execute function private.set_updated_at();

alter table public.platform_settings enable row level security;
revoke all on table public.platform_settings from anon, authenticated;
grant select, update on table public.platform_settings to authenticated;

drop policy if exists platform_settings_select_admin on public.platform_settings;
create policy platform_settings_select_admin
  on public.platform_settings
  for select
  to authenticated
  using (
    exists (
      select 1
      from public.profiles p
      where p.user_id = (select auth.uid())
        and p.role = 'Admin'
        and not p.is_locked
    )
  );

drop policy if exists platform_settings_update_admin on public.platform_settings;
create policy platform_settings_update_admin
  on public.platform_settings
  for update
  to authenticated
  using (
    exists (
      select 1
      from public.profiles p
      where p.user_id = (select auth.uid())
        and p.role = 'Admin'
        and not p.is_locked
    )
  )
  with check (updated_by = (select auth.uid()));
