-- Database-backed requester, claim and mission flow.
-- Sensitive address/coordinates live outside the public booking row and are
-- returned only through guarded functions after the appropriate transition.

create table if not exists public.bookings (
  booking_id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(user_id) on delete cascade,
  language_id bigint not null references public.languages(language_id) on delete restrict,
  category_id bigint not null references public.categories(category_id) on delete restrict,
  description text not null default '',
  location_name text not null,
  area_latitude numeric(9, 6),
  area_longitude numeric(9, 6),
  urgency text not null default 'immediate',
  status text not null default 'open',
  scheduled_at timestamptz,
  expires_at timestamptz not null,
  interpreter_id uuid references public.profiles(user_id) on delete set null,
  claimed_at timestamptz,
  requester_confirmed_at timestamptz,
  started_at timestamptz,
  ended_at timestamptz,
  user_confirmed_done_at timestamptz,
  interpreter_confirmed_done_at timestamptz,
  cancelled_by text,
  cancel_reason text,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  constraint bookings_urgency_check
    check (urgency in ('immediate', 'scheduled')),
  constraint bookings_status_check
    check (status in ('open', 'claimed', 'in_progress', 'completed', 'cancelled', 'expired')),
  constraint bookings_cancelled_by_check
    check (cancelled_by is null or cancelled_by in ('user', 'interpreter', 'manager', 'system')),
  constraint bookings_scheduled_at_check
    check ((urgency = 'immediate' and scheduled_at is null) or (urgency = 'scheduled' and scheduled_at is not null)),
  constraint bookings_coordinates_are_private_check
    check (length(location_name) between 1 and 200),
  constraint bookings_area_latitude_check
    check (area_latitude is null or area_latitude between -90 and 90),
  constraint bookings_area_longitude_check
    check (area_longitude is null or area_longitude between -180 and 180),
  constraint bookings_cancel_reason_check
    check (cancel_reason is null or length(cancel_reason) between 1 and 500)
);

create table if not exists public.booking_private_details (
  booking_id bigint primary key references public.bookings(booking_id) on delete cascade,
  exact_address text not null,
  latitude numeric(9, 6),
  longitude numeric(9, 6),
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  constraint booking_private_details_address_check
    check (length(exact_address) between 1 and 500),
  constraint booking_private_details_latitude_check
    check (latitude is null or latitude between -90 and 90),
  constraint booking_private_details_longitude_check
    check (longitude is null or longitude between -180 and 180)
);

create table if not exists public.mission_locations (
  booking_id bigint not null references public.bookings(booking_id) on delete cascade,
  actor_id uuid not null references public.profiles(user_id) on delete cascade,
  latitude numeric(9, 6) not null,
  longitude numeric(9, 6) not null,
  updated_at timestamptz not null default timezone('utc', now()),
  primary key (booking_id, actor_id),
  constraint mission_locations_latitude_check
    check (latitude between -90 and 90),
  constraint mission_locations_longitude_check
    check (longitude between -180 and 180)
);

create index if not exists bookings_user_id_idx on public.bookings(user_id);
create index if not exists bookings_interpreter_id_idx on public.bookings(interpreter_id);
create index if not exists bookings_open_pool_idx
  on public.bookings(status, expires_at, language_id, category_id)
  where status = 'open';
create index if not exists mission_locations_booking_id_idx on public.mission_locations(booking_id);

alter table public.bookings enable row level security;
alter table public.booking_private_details enable row level security;
alter table public.mission_locations enable row level security;

revoke all on table public.bookings from anon;
revoke all on table public.booking_private_details from anon;
revoke all on table public.mission_locations from anon;
revoke all on table public.bookings from authenticated;
revoke all on table public.booking_private_details from authenticated;
revoke all on table public.mission_locations from authenticated;
grant select on table public.bookings to authenticated;
grant insert (
  user_id,
  language_id,
  category_id,
  description,
  location_name,
  urgency,
  scheduled_at,
  expires_at
) on table public.bookings to authenticated;
grant usage, select on sequence public.bookings_booking_id_seq to authenticated;
grant insert on table public.booking_private_details to authenticated;

drop policy if exists bookings_select_visible_to_actor on public.bookings;
create policy bookings_select_visible_to_actor
  on public.bookings
  for select
  to authenticated
  using (
    user_id = (select auth.uid())
    or interpreter_id = (select auth.uid())
    or exists (
      select 1
      from public.profiles p
      where p.user_id = (select auth.uid())
        and p.role in ('Manager', 'Admin')
    )
    or (
      status = 'open'
      and expires_at > timezone('utc', now())
      and exists (
        select 1
        from public.profiles actor
        where actor.user_id = (select auth.uid())
          and actor.role = 'Interpreter'
          and actor.is_locked = false
      )
      and exists (
        select 1
        from public.interpreter_applications a
        join public.interpreter_application_languages al
          on al.application_id = a.application_id
        join public.interpreter_application_categories ac
          on ac.application_id = a.application_id
        where a.user_id = (select auth.uid())
          and a.status = 'approved'
          and al.language_id = bookings.language_id
          and ac.category_id = bookings.category_id
      )
    )
  );

drop policy if exists bookings_insert_own on public.bookings;
create policy bookings_insert_own
  on public.bookings
  for insert
  to authenticated
  with check ((select auth.uid()) = user_id);

drop policy if exists booking_private_details_insert_own on public.booking_private_details;
create policy booking_private_details_insert_own
  on public.booking_private_details
  for insert
  to authenticated
  with check (
    exists (
      select 1
      from public.bookings b
      where b.booking_id = booking_private_details.booking_id
        and b.user_id = (select auth.uid())
    )
  );

drop policy if exists booking_private_details_select_authorized on public.booking_private_details;
create policy booking_private_details_select_authorized
  on public.booking_private_details
  for select
  to authenticated
  using (
    exists (
      select 1
      from public.bookings b
      where b.booking_id = booking_private_details.booking_id
        and (
          b.user_id = (select auth.uid())
          or (
            b.interpreter_id = (select auth.uid())
            and b.requester_confirmed_at is not null
          )
          or exists (
            select 1
            from public.profiles p
            where p.user_id = (select auth.uid())
              and p.role in ('Manager', 'Admin')
          )
        )
    )
  );

drop policy if exists mission_locations_no_direct_select on public.mission_locations;
drop policy if exists mission_locations_no_direct_insert on public.mission_locations;
drop policy if exists mission_locations_no_direct_update on public.mission_locations;
drop policy if exists mission_locations_no_direct_delete on public.mission_locations;

create trigger bookings_set_updated_at
  before update on public.bookings
  for each row
  execute function private.set_updated_at();

create trigger booking_private_details_set_updated_at
  before update on public.booking_private_details
  for each row
  execute function private.set_updated_at();

create or replace function public.create_booking(
  p_language_code text,
  p_category_code text,
  p_description text,
  p_location_name text,
  p_exact_address text,
  p_latitude numeric,
  p_longitude numeric,
  p_urgency text,
  p_scheduled_at timestamptz default null
)
returns bigint
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  current_user_id uuid := (select auth.uid());
  selected_language_id bigint;
  selected_category_id bigint;
  new_booking_id bigint;
  calculated_expiry timestamptz;
begin
  if current_user_id is null then
    raise exception 'not_authenticated' using errcode = '42501';
  end if;

  if p_urgency not in ('immediate', 'scheduled') then
    raise exception 'invalid_urgency';
  end if;

  if p_urgency = 'scheduled' and p_scheduled_at is null then
    raise exception 'scheduled_at_required';
  end if;

  if p_urgency = 'scheduled'
     and (p_scheduled_at at time zone 'Asia/Bangkok')::date < timezone('Asia/Bangkok', now())::date + 1 then
    raise exception 'scheduled_at_must_be_next_day_or_later';
  end if;

  select language_id into selected_language_id
  from public.languages
  where language_code = p_language_code and is_active = true;

  select category_id into selected_category_id
  from public.categories
  where category_code = p_category_code and is_active = true;

  if selected_language_id is null or selected_category_id is null then
    raise exception 'unsupported_reference_value';
  end if;

  calculated_expiry := case
    when p_urgency = 'scheduled' then p_scheduled_at
    else timezone('utc', now()) + interval '30 minutes'
  end;

  insert into public.bookings (
    user_id, language_id, category_id, description, location_name,
    area_latitude, area_longitude,
    urgency, status, scheduled_at, expires_at
  )
  values (
    current_user_id,
    selected_language_id,
    selected_category_id,
    trim(coalesce(p_description, '')),
    'Approximate area',
    round(p_latitude, 2),
    round(p_longitude, 2),
    p_urgency,
    'open',
    p_scheduled_at,
    calculated_expiry
  )
  returning booking_id into new_booking_id;

  insert into public.booking_private_details (booking_id, exact_address, latitude, longitude)
  values (new_booking_id, trim(p_exact_address), p_latitude, p_longitude);

  return new_booking_id;
end;
$$;

create or replace function public.claim_booking(p_booking_id bigint)
returns bigint
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  current_user_id uuid := (select auth.uid());
  target public.bookings;
begin
  if current_user_id is null then
    raise exception 'not_authenticated' using errcode = '42501';
  end if;

  select * into target
  from public.bookings
  where booking_id = p_booking_id
  for update;

  if not found then
    raise exception 'booking_not_found';
  end if;

  if target.status <> 'open' or target.expires_at <= timezone('utc', now()) then
    if target.status = 'open' and target.expires_at <= timezone('utc', now()) then
      update public.bookings
      set status = 'expired', cancelled_by = 'system', cancel_reason = 'No interpreter claimed the request before its deadline.'
      where booking_id = p_booking_id;
    end if;
    raise exception 'booking_not_available';
  end if;

  if target.user_id = current_user_id then
    raise exception 'cannot_claim_own_booking';
  end if;

  if not exists (
    select 1 from public.profiles p
    where p.user_id = current_user_id and p.role = 'Interpreter' and p.is_locked = false
  ) then
    raise exception 'interpreter_role_required';
  end if;

  if not exists (
    select 1
    from public.interpreter_applications a
    join public.interpreter_application_languages al on al.application_id = a.application_id
    join public.interpreter_application_categories ac on ac.application_id = a.application_id
    where a.user_id = current_user_id
      and a.status = 'approved'
      and al.language_id = target.language_id
      and ac.category_id = target.category_id
  ) then
    raise exception 'interpreter_skill_mismatch';
  end if;

  if exists (
    select 1 from public.bookings b
    where b.interpreter_id = current_user_id
      and b.status in ('claimed', 'in_progress')
  ) then
    raise exception 'active_assignment_exists';
  end if;

  update public.bookings
  set interpreter_id = current_user_id,
      status = 'claimed',
      claimed_at = coalesce(claimed_at, timezone('utc', now())),
      requester_confirmed_at = null
  where booking_id = p_booking_id;

  return p_booking_id;
end;
$$;

create or replace function public.confirm_booking_interpreter(p_booking_id bigint)
returns void
language plpgsql
security definer
set search_path = public, pg_temp
as $$
begin
  if (select auth.uid()) is null then
    raise exception 'not_authenticated' using errcode = '42501';
  end if;

  update public.bookings
  set requester_confirmed_at = coalesce(requester_confirmed_at, timezone('utc', now()))
  where booking_id = p_booking_id
    and user_id = (select auth.uid())
    and status = 'claimed'
    and interpreter_id is not null;

  if not found then
    raise exception 'booking_confirmation_not_allowed';
  end if;
end;
$$;

create or replace function public.start_booking(p_booking_id bigint)
returns void
language plpgsql
security definer
set search_path = public, pg_temp
as $$
begin
  if (select auth.uid()) is null then
    raise exception 'not_authenticated' using errcode = '42501';
  end if;

  update public.bookings
  set status = 'in_progress', started_at = coalesce(started_at, timezone('utc', now()))
  where booking_id = p_booking_id
    and interpreter_id = (select auth.uid())
    and status = 'claimed'
    and requester_confirmed_at is not null;

  if not found then
    raise exception 'booking_start_not_allowed';
  end if;
end;
$$;

create or replace function public.confirm_booking_completion(p_booking_id bigint)
returns void
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  target public.bookings;
  current_user_id uuid := (select auth.uid());
  confirmation_time timestamptz := timezone('utc', now());
begin
  if current_user_id is null then
    raise exception 'not_authenticated' using errcode = '42501';
  end if;

  select * into target from public.bookings where booking_id = p_booking_id for update;
  if not found or target.status <> 'in_progress' then
    raise exception 'booking_completion_not_allowed';
  end if;

  if target.user_id = current_user_id then
    update public.bookings
    set user_confirmed_done_at = coalesce(user_confirmed_done_at, confirmation_time)
    where booking_id = p_booking_id;
  elsif target.interpreter_id = current_user_id then
    update public.bookings
    set interpreter_confirmed_done_at = coalesce(interpreter_confirmed_done_at, confirmation_time)
    where booking_id = p_booking_id;
  else
    raise exception 'booking_actor_not_allowed' using errcode = '42501';
  end if;

  update public.bookings
  set status = 'completed', ended_at = coalesce(ended_at, confirmation_time)
  where booking_id = p_booking_id
    and user_confirmed_done_at is not null
    and interpreter_confirmed_done_at is not null;
end;
$$;

create or replace function public.cancel_booking(p_booking_id bigint, p_reason text)
returns void
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  target public.bookings;
  current_user_id uuid := (select auth.uid());
  trimmed_reason text := trim(coalesce(p_reason, ''));
begin
  if current_user_id is null then
    raise exception 'not_authenticated' using errcode = '42501';
  end if;
  if trimmed_reason = '' then
    raise exception 'cancel_reason_required';
  end if;

  select * into target from public.bookings where booking_id = p_booking_id for update;
  if not found then
    raise exception 'booking_not_found';
  end if;

  if target.user_id = current_user_id then
    if target.status in ('completed', 'cancelled', 'expired') then
      raise exception 'booking_cannot_be_cancelled';
    end if;
    update public.bookings
    set status = 'cancelled', cancelled_by = 'user', cancel_reason = trimmed_reason
    where booking_id = p_booking_id;
    return;
  end if;

  if target.interpreter_id <> current_user_id then
    raise exception 'booking_actor_not_allowed' using errcode = '42501';
  end if;

  if target.status = 'claimed' then
    if target.expires_at > timezone('utc', now()) then
      update public.bookings
      set status = 'open', interpreter_id = null, claimed_at = null, requester_confirmed_at = null
      where booking_id = p_booking_id;
    else
      update public.bookings
      set status = 'expired', cancelled_by = 'system', cancel_reason = 'The original request deadline passed.'
      where booking_id = p_booking_id;
    end if;
    return;
  end if;

  if target.status = 'in_progress' then
    update public.bookings
    set status = 'cancelled', cancelled_by = 'interpreter', cancel_reason = trimmed_reason
    where booking_id = p_booking_id;
    return;
  end if;

  raise exception 'booking_cannot_be_withdrawn';
end;
$$;

create or replace function public.update_booking_details(
  p_booking_id bigint,
  p_language_code text,
  p_category_code text,
  p_description text,
  p_location_name text,
  p_exact_address text
)
returns void
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  selected_language_id bigint;
  selected_category_id bigint;
begin
  select language_id into selected_language_id from public.languages where language_code = p_language_code and is_active = true;
  select category_id into selected_category_id from public.categories where category_code = p_category_code and is_active = true;
  if selected_language_id is null or selected_category_id is null then
    raise exception 'unsupported_reference_value';
  end if;

  update public.bookings
  set language_id = selected_language_id,
      category_id = selected_category_id,
      description = trim(coalesce(p_description, '')),
      location_name = 'Approximate area'
  where booking_id = p_booking_id
    and user_id = (select auth.uid())
    and status in ('open', 'claimed');

  if not found then
    raise exception 'booking_update_not_allowed';
  end if;

  update public.booking_private_details
  set exact_address = trim(p_exact_address)
  where booking_id = p_booking_id;
end;
$$;

create or replace function public.get_booking_private_details(p_booking_id bigint)
returns table (
  booking_id bigint,
  exact_address text,
  latitude numeric,
  longitude numeric
)
language sql
security definer
set search_path = public, pg_temp
as $$
  select d.booking_id, d.exact_address, d.latitude, d.longitude
  from public.booking_private_details d
  join public.bookings b on b.booking_id = d.booking_id
  where d.booking_id = p_booking_id
    and (
      b.user_id = (select auth.uid())
      or (b.interpreter_id = (select auth.uid()) and b.requester_confirmed_at is not null)
      or exists (
        select 1 from public.profiles p
        where p.user_id = (select auth.uid()) and p.role in ('Manager', 'Admin')
      )
    );
$$;

create or replace function public.get_booking_contacts(p_booking_id bigint)
returns table (
  contact_role text,
  user_id uuid,
  display_name text,
  phone text,
  extra_contact text
)
language sql
security definer
set search_path = public, pg_temp
as $$
  with target as (
    select b.booking_id, b.user_id as requester_id, b.interpreter_id, b.requester_confirmed_at
    from public.bookings b
    where b.booking_id = p_booking_id
  )
  select 'requester', p.user_id,
         trim(concat(p.first_name, ' ', p.last_name)),
         p.phone,
         null::text
  from target t
  join public.profiles p on p.user_id = t.requester_id
  where (
       t.requester_id = (select auth.uid())
       or (t.interpreter_id = (select auth.uid()) and t.requester_confirmed_at is not null)
       or exists (
         select 1 from public.profiles actor
         where actor.user_id = (select auth.uid()) and actor.role in ('Manager', 'Admin')
       )
     )
  union all
  select 'interpreter', p.user_id,
         trim(concat(p.first_name, ' ', p.last_name)),
         case
           when t.interpreter_id = (select auth.uid())
             or t.requester_confirmed_at is not null
             or exists (
               select 1 from public.profiles actor
               where actor.user_id = (select auth.uid()) and actor.role in ('Manager', 'Admin')
             )
             then p.phone
           else null
         end,
         case
           when t.interpreter_id = (select auth.uid())
             or t.requester_confirmed_at is not null
             or exists (
               select 1 from public.profiles actor
               where actor.user_id = (select auth.uid()) and actor.role in ('Manager', 'Admin')
             )
             then a.extra_contact
           else null
         end
  from target t
  join public.profiles p on p.user_id = t.interpreter_id
  left join lateral (
    select ia.extra_contact
    from public.interpreter_applications ia
    where ia.user_id = p.user_id and ia.status = 'approved'
    order by ia.reviewed_at desc nulls last, ia.application_id desc
    limit 1
  ) a on true
  where t.interpreter_id is not null
    and (
      t.interpreter_id = (select auth.uid())
      or t.requester_id = (select auth.uid())
      or exists (
        select 1 from public.profiles actor
        where actor.user_id = (select auth.uid()) and actor.role in ('Manager', 'Admin')
      )
    );
$$;

create or replace function public.save_mission_location(
  p_booking_id bigint,
  p_latitude numeric,
  p_longitude numeric
)
returns void
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  current_user_id uuid := (select auth.uid());
begin
  if current_user_id is null then
    raise exception 'not_authenticated' using errcode = '42501';
  end if;

  if p_latitude not between -90 and 90 or p_longitude not between -180 and 180 then
    raise exception 'invalid_coordinates';
  end if;

  if not exists (
    select 1 from public.bookings b
    where b.booking_id = p_booking_id
      and b.status in ('open', 'claimed', 'in_progress')
      and (b.user_id = current_user_id or b.interpreter_id = current_user_id)
  ) then
    raise exception 'location_update_not_allowed' using errcode = '42501';
  end if;

  insert into public.mission_locations (booking_id, actor_id, latitude, longitude, updated_at)
  values (p_booking_id, current_user_id, p_latitude, p_longitude, timezone('utc', now()))
  on conflict (booking_id, actor_id) do update
  set latitude = excluded.latitude,
      longitude = excluded.longitude,
      updated_at = excluded.updated_at;
end;
$$;

create or replace function public.get_mission_locations(p_booking_id bigint)
returns table (
  actor_id uuid,
  latitude numeric,
  longitude numeric,
  updated_at timestamptz
)
language sql
security definer
set search_path = public, pg_temp
as $$
  select ml.actor_id, ml.latitude, ml.longitude, ml.updated_at
  from public.mission_locations ml
  join public.bookings b on b.booking_id = ml.booking_id
  where ml.booking_id = p_booking_id
    and (
      ml.actor_id = (select auth.uid())
      or (
        b.requester_confirmed_at is not null
        and (b.user_id = (select auth.uid()) or b.interpreter_id = (select auth.uid()))
      )
    );
$$;

revoke all on function public.create_booking(text, text, text, text, text, numeric, numeric, text, timestamptz) from public;
revoke all on function public.claim_booking(bigint) from public;
revoke all on function public.confirm_booking_interpreter(bigint) from public;
revoke all on function public.start_booking(bigint) from public;
revoke all on function public.confirm_booking_completion(bigint) from public;
revoke all on function public.cancel_booking(bigint, text) from public;
revoke all on function public.update_booking_details(bigint, text, text, text, text, text) from public;
revoke all on function public.get_booking_private_details(bigint) from public;
revoke all on function public.get_booking_contacts(bigint) from public;
revoke all on function public.save_mission_location(bigint, numeric, numeric) from public;
revoke all on function public.get_mission_locations(bigint) from public;

grant execute on function public.create_booking(text, text, text, text, text, numeric, numeric, text, timestamptz) to authenticated;
grant execute on function public.claim_booking(bigint) to authenticated;
grant execute on function public.confirm_booking_interpreter(bigint) to authenticated;
grant execute on function public.start_booking(bigint) to authenticated;
grant execute on function public.confirm_booking_completion(bigint) to authenticated;
grant execute on function public.cancel_booking(bigint, text) to authenticated;
grant execute on function public.update_booking_details(bigint, text, text, text, text, text) to authenticated;
grant execute on function public.get_booking_private_details(bigint) to authenticated;
grant execute on function public.get_booking_contacts(bigint) to authenticated;
grant execute on function public.save_mission_location(bigint, numeric, numeric) to authenticated;
grant execute on function public.get_mission_locations(bigint) to authenticated;
