-- Database-backed requester reviews for completed interpreter assignments.
-- A requester can submit one review per completed booking. The reviewer and
-- reviewee are always derived from the booking inside the RPC; clients never
-- choose either identity.

create table if not exists public.reviews (
  review_id bigint generated by default as identity primary key,
  booking_id bigint not null references public.bookings(booking_id) on delete restrict,
  reviewer_id uuid not null references public.profiles(user_id) on delete restrict,
  reviewee_id uuid not null references public.profiles(user_id) on delete restrict,
  rating smallint not null,
  comment text,
  created_at timestamptz not null default timezone('utc', now()),
  constraint reviews_rating_check check (rating between 1 and 5),
  constraint reviews_comment_check check (comment is null or length(trim(comment)) between 1 and 1000),
  constraint reviews_reviewer_reviewee_check check (reviewer_id <> reviewee_id),
  constraint reviews_one_per_booking_reviewer unique (booking_id, reviewer_id)
);

create index if not exists reviews_booking_id_idx on public.reviews(booking_id);
create index if not exists reviews_reviewer_id_idx on public.reviews(reviewer_id);
create index if not exists reviews_reviewee_id_idx on public.reviews(reviewee_id);

alter table public.reviews enable row level security;

revoke all on table public.reviews from anon;
revoke all on table public.reviews from authenticated;
grant select on table public.reviews to authenticated;

drop policy if exists reviews_select_involved_or_staff on public.reviews;
create policy reviews_select_involved_or_staff
  on public.reviews
  for select
  to authenticated
  using (
    reviewer_id = (select auth.uid())
    or reviewee_id = (select auth.uid())
    or exists (
      select 1
      from public.profiles actor
      where actor.user_id = (select auth.uid())
        and actor.role in ('Manager', 'Admin')
        and actor.is_locked = false
        and actor.deleted_at is null
    )
  );

create or replace function private.validate_review_row()
returns trigger
language plpgsql
set search_path = public, pg_temp
as $$
declare
  target public.bookings;
begin
  select * into target
  from public.bookings
  where booking_id = new.booking_id;

  if not found then
    raise exception 'booking_not_found';
  end if;

  if target.status <> 'completed'
     or target.interpreter_id is null
     or target.user_id <> new.reviewer_id
     or target.interpreter_id <> new.reviewee_id then
    raise exception 'review_not_allowed';
  end if;

  return new;
end;
$$;

drop trigger if exists reviews_validate_target on public.reviews;
create trigger reviews_validate_target
  before insert on public.reviews
  for each row
  execute function private.validate_review_row();

create or replace function public.create_review(
  p_booking_id bigint,
  p_rating smallint,
  p_comment text default null
)
returns bigint
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  current_user_id uuid := (select auth.uid());
  target public.bookings;
  review_id_value bigint;
  trimmed_comment text := nullif(trim(coalesce(p_comment, '')), '');
begin
  if current_user_id is null then
    raise exception 'not_authenticated' using errcode = '42501';
  end if;

  if p_rating is null or p_rating not between 1 and 5 then
    raise exception 'review_rating_invalid';
  end if;

  if trimmed_comment is not null and length(trimmed_comment) > 1000 then
    raise exception 'review_comment_too_long';
  end if;

  select * into target
  from public.bookings
  where booking_id = p_booking_id
  for share;

  if not found then
    raise exception 'booking_not_found';
  end if;

  if target.status <> 'completed'
     or target.user_id <> current_user_id
     or target.interpreter_id is null then
    raise exception 'review_not_allowed';
  end if;

  begin
    insert into public.reviews (booking_id, reviewer_id, reviewee_id, rating, comment)
    values (p_booking_id, current_user_id, target.interpreter_id, p_rating, trimmed_comment)
    returning review_id into review_id_value;
  exception
    when unique_violation then
      raise exception 'review_already_exists' using errcode = '23505';
  end;

  return review_id_value;
end;
$$;

create or replace function public.get_booking_review(p_booking_id bigint)
returns table (
  review_id bigint,
  booking_id bigint,
  reviewer_id uuid,
  reviewee_id uuid,
  rating smallint,
  comment text,
  created_at timestamptz
)
language sql
security definer
stable
set search_path = public, pg_temp
as $$
  select r.review_id,
         r.booking_id,
         r.reviewer_id,
         r.reviewee_id,
         r.rating,
         r.comment,
         r.created_at
  from public.reviews r
  join public.bookings b on b.booking_id = r.booking_id
  where (select auth.uid()) is not null
    and r.booking_id = p_booking_id
    and (
      b.user_id = (select auth.uid())
      or b.interpreter_id = (select auth.uid())
      or exists (
        select 1
        from public.profiles actor
        where actor.user_id = (select auth.uid())
          and actor.role in ('Manager', 'Admin')
          and actor.is_locked = false
          and actor.deleted_at is null
      )
    );
$$;

create or replace function public.get_interpreter_rating(p_interpreter_id uuid)
returns table (
  average_rating numeric,
  review_count bigint,
  completed_job_count bigint
)
language sql
security definer
stable
set search_path = public, pg_temp
as $$
  select coalesce((
           select round(avg(r.rating)::numeric, 2)
           from public.reviews r
           where r.reviewee_id = p.user_id
         ), 0)::numeric(3, 2) as average_rating,
         (
           select count(*)
           from public.reviews r
           where r.reviewee_id = p.user_id
         ) as review_count,
         (
           select count(*)
           from public.bookings b
           where b.interpreter_id = p.user_id
             and b.status = 'completed'
         ) as completed_job_count
  from public.profiles p
  where (select auth.uid()) is not null
    and p.user_id = p_interpreter_id
    and p.role = 'Interpreter'
    and p.deleted_at is null;
$$;

create or replace function public.get_interpreter_reviews(p_interpreter_id uuid)
returns table (
  review_id bigint,
  booking_id bigint,
  reviewer_id uuid,
  reviewee_id uuid,
  rating smallint,
  comment text,
  created_at timestamptz
)
language sql
security definer
stable
set search_path = public, pg_temp
as $$
  select r.review_id,
         r.booking_id,
         r.reviewer_id,
         r.reviewee_id,
         r.rating,
         r.comment,
         r.created_at
  from public.reviews r
  where (select auth.uid()) is not null
    and r.reviewee_id = p_interpreter_id
    and (
      r.reviewee_id = (select auth.uid())
      or exists (
        select 1
        from public.profiles actor
        where actor.user_id = (select auth.uid())
          and actor.role in ('Manager', 'Admin')
          and actor.is_locked = false
          and actor.deleted_at is null
      )
    )
  order by r.created_at desc, r.review_id desc;
$$;

revoke all on function public.create_review(bigint, smallint, text) from public;
revoke all on function public.get_booking_review(bigint) from public;
revoke all on function public.get_interpreter_rating(uuid) from public;
revoke all on function public.get_interpreter_reviews(uuid) from public;

grant execute on function public.create_review(bigint, smallint, text) to authenticated;
grant execute on function public.get_booking_review(bigint) to authenticated;
grant execute on function public.get_interpreter_rating(uuid) to authenticated;
grant execute on function public.get_interpreter_reviews(uuid) to authenticated;
