create table if not exists public.reports (
  report_id bigint generated by default as identity primary key,

  report_type text not null
    check (report_type in ('user', 'interpreter', 'system')),

  category text not null,
  title text not null
    check (length(trim(title)) between 1 and 200),

  description text not null
    check (length(trim(description)) between 1 and 5000),

  severity text not null default 'medium'
    check (severity in ('medium', 'high', 'critical')),

  status text not null default 'new'
    check (status in ('new', 'in_progress', 'escalated', 'resolved', 'dismissed')),

  resolution_action text not null default 'none'
    check (resolution_action in ('none', 'fixed', 'warned', 'locked', 'hard_banned', 'unlocked')),

  resolution_note text,

  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  resolved_at timestamptz,

  reporter_id uuid not null,
  reported_user_id uuid,
  assigned_to uuid,
  booking_id bigint,

  constraint reports_reporter_fk
    foreign key (reporter_id)
    references public.profiles(user_id)
    on delete restrict,

  constraint reports_reported_user_fk
    foreign key (reported_user_id)
    references public.profiles(user_id)
    on delete restrict,

  constraint reports_assigned_to_fk
    foreign key (assigned_to)
    references public.profiles(user_id)
    on delete restrict,

  constraint reports_booking_fk
    foreign key (booking_id)
    references public.bookings(booking_id)
    on delete restrict,

  constraint reports_type_target_check check (
    (report_type = 'system' and reported_user_id is null)
    or
    (report_type in ('user', 'interpreter') and reported_user_id is not null)
  ),

  constraint reports_reporter_target_check check (
    reported_user_id is null or reporter_id <> reported_user_id
  )
);

create index if not exists reports_reporter_id_idx
  on public.reports(reporter_id);

create index if not exists reports_reported_user_id_idx
  on public.reports(reported_user_id);

create index if not exists reports_assigned_to_idx
  on public.reports(assigned_to);

create index if not exists reports_booking_id_idx
  on public.reports(booking_id);

create index if not exists reports_status_idx
  on public.reports(status);

create index if not exists reports_type_idx
  on public.reports(report_type);

alter table public.reports enable row level security;

drop trigger if exists reports_set_updated_at on public.reports;
create trigger reports_set_updated_at
  before update on public.reports
  for each row
  execute function private.set_updated_at();
